#!/bin/bash

NAME=("$1")
START=("$2")
END=("$3")

CONF_EQUIL="${NAME}_equil.conf"
CONF_MIN="${NAME}_min.conf"

TOP="${NAME}_CG.top"
NEWTOP="new${NAME}_CG.top"
XYZMIN="${NAME}_CG.min.xyz"
DCD="${NAME}_CG.dcd"

printf "name of structure: %s\n" "$NAME"
printf "quantity of iterations: %d\n" "$ITER"
printf "names of config(equil, min) files: %s, %s\n" "$CONF_EQUIL" "$CONF_MIN"
printf "name of TOP file: %s\n" "$TOP"
printf "name of newTOP file: %s\n" "$NEWTOP"

cd $NAME/

for((i = $START; i <= $END; i++))
do
	#simulation with new parameters
	./../../../../bin/mrg-cg2 $CONF_EQUIL
	cp -f output/$DCD input/

	#finding new parameters using last cg dcd
	./../../../../bin/sop_par1 $CONF_EQUIL $i

	#check if newtop was created (sop_par1 finished)
	#if newtop wasn't created mrg-cg2 at the next iteration won't be executed 
	rm input/$NEWTOP
	cp -f output/"new${NAME}_CG${i}.top" input/$NEWTOP
done
