#!/bin/bash

NAME=("$1")
PAIR=("$2")

printf "name of structure: %s\n" "$NAME"

if [ $PAIR == "B" ]
then
	printf "pairtype: bonds\n"
elif [ $PAIR == "P" ]
then
	printf "pairtype: pairs\n"
else
	printf "ERROR: WRONG VALUE FOR PAIRTYPE\n"
fi

for param in "$@"
do
	if [ "$param" != "$NAME" ] && [ "$param" != "$PAIR" ];
	then
	count=$(( $count + 1 ))
	echo "#$count: $param frames"
	fi
done

printf "count = $count\n"

CONF_EQUIL="${NAME}_equil.conf"
CONF_MIN="${NAME}_min.conf"

TOP="${NAME}_CG.top"
NEWTOP="new${NAME}_CG.top"
XYZMIN="${NAME}_CG.min.xyz"

#printf "names of config(equil, min) files: %s, %s\n" "$CONF_EQUIL" "$CONF_MIN"
#printf "name of TOP file: %s\n" "$TOP"
#printf "name of newTOP file: %s\n" "$NEWTOP"

cd ../../
make
cd TopologyCreators/SOPParametrization/$NAME/


	#finding initial approximation of parameters and creating newtop
cp -f input/$TOP input/$NEWTOP


first_frame=0
last_frame=$first_frame

for param in "$@"
do
	if [ "$param" != "$NAME" ] && [ "$param" != "$PAIR" ];
	then
		let last_frame=$first_frame+$param
		./../../../../bin/sop_par0 $CONF_EQUIL 0 $PAIR $((first_frame + 1)) $last_frame
		rm input/$NEWTOP
		cp -f output/"new${NAME}_CG0.top" input/$NEWTOP
		mv -f output/dev0.dat output/dev${param}.dat
		mv -f output/meandev_disp0.dat output/meandev_disp${param}.dat
	fi
done
